# Generated by Django 3.0.4 on 2020-03-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_exampletwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
