# Generated by Django 3.0.4 on 2020-03-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_examplethree'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplethree',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
