# Generated by Django 3.0.4 on 2020-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_examplethree_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplethree',
            name='non_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='examplethree',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
