# Generated by Django 3.0.4 on 2020-03-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_auto_20200329_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplethree',
            name='non_icon',
        ),
    ]
